const BasketballQuizData = [
  {
    id: 1,
    question: "What is the highest governing body of basketball ?",
    optionOne: "EuroLeague",
    optionTwo: "NBA",
    optionThree: "FIBA",
    correctAnswer: "FIBA",
    selectedAnswer: " ",
    questionStatus: false,
  },
  {
    id: 2,
    question: "Kicking a basketball is what kind of foul?",
    optionOne: "Personal foul",
    optionTwo: "Flagrant foul",
    optionThree: "Technical foul",
    correctAnswer: "Technical foul",
    selectedAnswer: " ",
    questionStatus: false,
  },
  {
    id: 3,
    question: "A free throw is worth…",
    optionOne: "1 point",
    optionTwo: " 2 points",
    optionThree: "3 points",
    correctAnswer: "1 point",
    selectedAnswer: " ",
    questionStatus: false,
  },
  {
    id: 4,
    question: "What does BEEF mean?",
    optionOne: "Balance, Eyes, Elbow, Follow Through",
    optionTwo: "Basketball, Elbow, Endline, Free-Throw",
    optionThree: "Box and One, Euro Step, Elevator Screen, Field Goal",
    correctAnswer: "Balance, Eyes, Elbow, Follow Through",
    selectedAnswer: " ",
    questionStatus: false,
  },
  {
    id: 5,
    question: "The main responsibility of the “center” player is to…",
    optionOne: "make baskets",
    optionTwo: "steal the ball and block attacks",
    optionThree: "secure rebounds and defend the paint",
    correctAnswer: "secure rebounds and defend the paint",
    selectedAnswer: " ",
    questionStatus: false,
  },
];

export default BasketballQuizData;
